# Gush configuration file, any comments will be lost.
meta-header: "This file is part of Gush package.\n\n(c) 2013-2015 Luis Cordova <cordoval@gmail.com>\n\nThis source file is subject to the MIT license that is bundled\nwith this source code in the file LICENSE."
pr_type:
    - feature
    - bugfix
    - refactor
    - tests
    - remove
    - style
    - documentation
    - security
table-pr:
    fixed_tickets: ['Fixed Tickets', '']
    license: [License, MIT]
base: '1.0'
repo_adapter: github
issue_tracker: github
repo_org: gushphp
repo_name: gush
issue_project_org: gushphp
issue_project_name: gush
