#!/usr/bin/env bash

bldr=$(which bldr)

if [ -x "$bldr" ] ; then
    $bldr install
    $bldr build $1
else
    if [ ! -f ./bldr.phar ]; then
        curl -sS http://bldr.io/installer | php
    fi

    ./bldr.phar install
    ./bldr.phar build $1
fi
