#!/usr/bin/env php
<?php

/**
 * This file is part of Gush.
 *
 * (c) Luis Cordova <cordoval@gmail.com>
 *
 * This source file is subject to the MIT license that is bundled
 * with this source code in the file LICENSE.
 */
    
require_once __DIR__.'/vendor/autoload.php';

error_reporting(-1);
ini_set('display_errors', 1);

$app = new Gush\Application();

foreach ($app->getCommands() as $command) {
    // run specific command with --format md
    $app->run();

    // craete md file on the right place
}

