#!/usr/bin/env php
<?php

/*
 * This file is part of Gush.
 *
 * (c) Luis Cordova <cordoval@gmail.com>
 *
 * This source file is subject to the MIT license that is bundled
 * with this source code in the file LICENSE.
 */

require __DIR__.'/vendor/autoload.php';

use Gush\ConfigFactory;
use Gush\ThirdParty\Bitbucket\BitbucketFactory;
use Gush\ThirdParty\Github\GitHubEnterpriseFactory;
use Gush\ThirdParty\Github\GitHubFactory;
use Gush\ThirdParty\Gitlab\GitLabFactory;

error_reporting(E_ALL);
ini_set('display_errors', 1);

$adapterFactory = new Gush\Factory\AdapterFactory();

$adapters = [
    'github' => [GitHubFactory::class, 'GitHub'],
    'github_enterprise' => [GitHubEnterpriseFactory::class, 'GitHub Enterprise'],
    'bitbucket' => [BitbucketFactory::class, 'Bitbucket'],
    'gitlab' => [GitLabFactory::class, 'GitLab']
];

foreach ($adapters as $adapterName => $adapter) {
    $adapterFactory->register($adapterName, $adapter[1], $adapter[0]);
}

if (false !== getenv('GUSH_CONFIG')) {
    $config = ConfigFactory::createConfig((string) getenv('GUSH_CONFIG'), (string) getenv('GUSH_LOCAL_CONFIG'));
} else {
    $config = ConfigFactory::createConfig(null, getcwd());
}

(new Gush\Application($adapterFactory, $config))->run();
