#!/usr/bin/env php
<?php

$vendorDir = __DIR__.'/vendor';

$file = $vendorDir.'/autoload.php';

if (file_exists($file)) {
    $autoload = require_once $file;
} else {
    echo 'Cannot find the vendor directory, have you executed composer install?';
    exit(1);
}

$app = new ManagerTools\Application();
$app->setCwd(__DIR__);
$app->add(new ManagerTools\Command\PullRequestCommand());
$app->run();