#!/usr/bin/env php
<?php

/*
 * This file is part of the Manager Tools.
 *
 * (c) Luis Cordova <cordoval@gmail.com>
 *
 * This source file is subject to the MIT license that is bundled
 * with this source code in the file LICENSE.
 */

$vendorDir = __DIR__.'/vendor';

$file = $vendorDir.'/autoload.php';

if (file_exists($file)) {
    $autoload = require_once $file;
} else {
    echo 'Cannot find the vendor directory, have you executed composer install?';
    exit(1);
}

$app = new ManagerTools\Application();
$app->add(new ManagerTools\Command\PullRequestCommand());
$app->add(new ManagerTools\Command\ReleaseCreateCommand());
$app->add(new ManagerTools\Command\ReleaseListCommand());
$app->add(new ManagerTools\Command\ReleaseRemoveCommand());
$app->run();
